version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    env_file:
      - .docker/dev/.env
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '0.0.0.0', '--silent']
      interval: 10s
      retries: 10
      start_period: 10s
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_TCP_PORT=${DB_PORT}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - store_volume:/var/lib/mysql
    networks:
      - store_network

  # adminer:
  #   container_name: adminer
  #   image: adminer
  #   restart: always
  #   env_file:
  #       - .docker/dev/.env
  #       - .env
  #   environment:
  #     ADMINER_DEFAULT_SERVER: ${DB_HOST}:${DB_PORT}
  #     ADMINER_DESIGN: galkaev
  # depends_on:
  #   mysql:
  #     condition: service_healthy
  # networks:
  #   - swapi_network
  # links:
  #   - mysql
  # ports:
  #   - 8080:8080

  store:
    build:
      context: .
      dockerfile: .docker/dev/Dockerfile
    image: store
    container_name: store
    command: sh -c "npm run migrate && npm run seed && npm run start"
    env_file:
      - .docker/dev/.env
      - .env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://store:${PORT:-3000}/api/health']
      interval: 10s
      retries: 10
      start_period: 10s
    environment:
      - PORT=${PORT:-3000}
      - DB_HOST=mysql
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASS}@mysql:${DB_PORT}/${DB_NAME}
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - store_network
    links:
      - mysql
    ports:
      - ${PORT:-3000}:${PORT:-3000}

volumes:
  store_volume:
    name: store_volume
    driver: local

networks:
  store_network:
    name: store_network
    driver: bridge
